### ISSUE TITLE
error in export current animation & batch export 

### ISSUE THREAD

**Issue by b4zz4** [ray-hplus/inkscape-animation#2] opened 2016-04-21 21:44 UTC
```
Traceback (most recent call last):
  File "iaps_exanim.py", line 40, in <module>
    _main()
  File "iaps_exanim.py", line 36, in _main
    e.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 215, in affect
    self.effect()
  File "iaps_exanim.py", line 30, in effect
    a = AnimationExport( self, self.current_layer, path, make_gif, gif_rate, frame_w, frame_h, use_frame_wh, self.options.debug )
  File "/home/edu/.config/inkscape/extensions/animationset/AnimationExport.py", line 40, in __init__
    self.name = self.get_animation_name()
  File "/home/edu/.config/inkscape/extensions/animationset/AnimationExport.py", line 74, in get_animation_name
    raw_name = self.top_layer.get('id')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by ray-hplus** [comment] 2016-04-27 23:51
Hi again, thank you for the crash report. This seems to happen when you trying to export animation without selecting any corresponding layer. I'll try to fix this later on. BTW, what version of Inkscape you're using?

**Comment by b4zz4** [comment] 2016-04-28 18:56
Inkscape 0.48.4 r9939

**Comment by b4zz4** [comment] 2016-04-28 19:02
I think that the problem this here:

```
    a = AnimationExport( self, n, actual_path, make_gif, gif_rate, frame_w, frame_h, use_frame_wh, self.options.debug )
    self.geom = self.get_bg_rect_geometry()
    x = self.effect.unittouu( self.bg_rect.get('x') )
```
That version of python have to use?

**Comment by b4zz4** [comment] 2016-04-30 20:02
in inkscape .91 It does not have problems, but does not export the animation :(

**Comment by Moini** [comment] 2016-06-08 01:15
I can confirm it does export a great set of png and svg files, but the gif that it produces only contains a white layer, and no other layers.

For one, the imagemagick regex for exporting > 10 images would be (on a Linux shell, don't know if it works on Windows): 
'frame_' + self.name + '_%d' + '.png' + "[1-" + str(numframes) + "]"

-> With this, I get a multi-layered gif.

Then, you also need to know that it will not work (i.e. crash) if you use an underscore in the name of the animation, as underscores are used to split off the index. Maybe starting the search from the end of the layer name would work better? Or just split the name with string.split('_') and take the last item from the resulting list.

-> Didn't test this yet. I'm happy only using names without spaces and underscores currently.

Unfortunately, the resulting gif is still entirely white, (multi-layered, but white), even if the png files in the directory are not.

**Comment by Moini** [comment] 2016-06-12 22:28
@b4zz4 : I think this version could work for you: https://github.com/Moini/inkscape-animation (the fix isn't beautiful, but works for me.)

**Comment by ray-hplus** [comment] 2016-06-13 03:57
Hello there. I've merged the fix into the master branch, so GIFs export should work now. As for the Inkscape version - 0.91 or greater is required, I've added it to README.

**Closed** 2016-06-13 04:08 UTC
